### ISSUE TITLE
szip compression parameters type checking fails in H5DATAIO

### ISSUE THREAD

**Issue by d-sot** [hdmf-dev/hdmf#166]
Currently szip can only be called without compression options.

Compression options for szip should be in the form of a tuple ('ec'|'nn', even integer 0-32). If a tuple, e.g. ```('ec',16)``` is passed to H5DATAIO:

```
>>> TypeError: incorrect type for 'compression_opts' (got 'tuple', expected 'int')
```

for

```
type(data) # numpy array
H5DataIO(data, chunks=(3,4,5,6)_A, compression="szip", compression_opts=('ec',16), shuffle=False)
```

**Comment by oruebel** [comment]
@d-sot https://github.com/hdmf-dev/hdmf/pull/167 should fix this. I also added some tests, but unfortunately I cannot run the test cases that use szip compression (i.e., the tests are automatically skipped) because SZIP is not installed with h5py by default, (because it is a Patent-encumbered filter). However, you should be able to run those tests locally if you have SZIP installed.
