### ISSUE TITLE
optional absolute paths for external links

### ISSUE THREAD

**Issue by bendichter** [hdmf-dev/hdmf#18]
We are changing paths of external links from absolute to relative (#17) (for Groups- for Datasets it was already set this way), which I think is the ideal default. However, I can also imagine a situation where the user would really want an absolute path. Imagine a lab stores acquisition data in a central read-only location and construct NWB files that link to this data for their everyday analysis. In this case they'll want the ability to move the analysis NWB files around without breaking the link. (I think I remember someone at AIBS talking about this kind of workflow). For this use-case, I think it would be useful to support absolute paths for external links are well. I think adding an option in `manager` or something would make sense. The complication arises when a user wants to create multiple links in a single NWB file, some of which are absolute and some of which are relative. For this, would it be possible to have a wrapper object similar to `HDF5IO` that would instruct `pynwb` which type of link should be used?

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by oruebel** [comment]
Allowing, absolute paths as an option is fine, but I honestly don't think it is a pressing need. Also, we don't have a specific use case for this right now. I would suggest to just close the issue for now, until we have an actual need for this. 

In terms of implementation, having a global option on ``HDF5IO`` should cover 99% of cases and would be simple to do. This should only require minimla changes to ``HDF5IO``.  If you want to control this for individual datasets then  you could update``H5DataIO`` and ``HDF5IO``. For groups (data_types) it's a bit trickier, but a simple workaround here would be to just call write twice, once with the data you want to have relative paths and once for the data that need absolute paths. I would ignore the case for controlling this for groups for now. 

For the lab data management scenario you describe, the approach to use absolute path will in most real cases not be sufficient and too brittle. Lab data management systems require a more advanced approaches to referencing external data. E.g., data management systems often stage data in/out of different storage devices, so datafiles are identified in those cases often by some sort of URL (or ID) rather than a posix filepath.

**Comment by bendichter** [comment]
I agree this isn't pressing until we have users that need it. Allowing this for datasets will cover most cases, since the objects you really care about linking are usually the data anyway.

If a user sees this issue and would like to request this feature, please ping us to reopen.
