### ISSUE TITLE
Don't invent object IDs if they are missing

### ISSUE THREAD

**Issue by t-b** [hdmf-dev/hdmf#341]
hdmf: 7d5ec7b0 (Add logging of build and hdf5 write process (#336), 2020-04-21)
pynwb: 78ded2eb (Clean up tests to remove conversion warnings and make pos arg -… (#1202), 2020-04-15)

I just fixed a bug where I named the object_id attribute wrong in IPNWB. Now my tests tried to check that already. But I realized that hdmf invents object IDs if they are not present, see 0160db33 (Fix missing object ID #114 and minor fixes (#115), 2019-07-29).

Reading https://pynwb.readthedocs.io/en/stable/tutorials/general/object_id.html I don't think it makes sense to invent object IDs. As IIUC the whole point is to be able to refer to the data in the NWB file, and that is not possible if we invent a new one everytime the file is opened.

**Comment by rly** [comment]
@t-b Sorry, I do not completely understand your comment.

If file A is written without object IDs and then opened by a recent version of PyNWB/HDMF and then written to file B (or overwrites file A), then yes, each neurodata_type will be written with a new `object_id` attribute. If file A is re-opened, then each neurodata_type will have a new, different object ID.

If file A is written with object IDs and then opened by PyNWB/HDMF, then the `object_id` will be the value that is read and will not change on write. 

Two files with the same data can have different object IDs; the object ID is not a hash of the data, but rather a pointer to a neurodata_type within an NWB file.

**Comment by rly** [comment]
Are you saying that if you open a file A without object IDs and write it to a new file B, and then reopen file A and write it to another file C, then the object IDs in B and C should be the same?

**Comment by t-b** [comment]
I'm never writing the file A without object IDs. I'm just reading it. And on reading the object IDs are different each time I open the file.

**Comment by oruebel** [comment]
@t-b  in some of the files from AIBS the object ids variables did not have the correct name (I believe they were callend objectID instead of object_id). Is this possibly related to that issue, i.e., if the ids have the wrong name than HDMF probably doesn't recognize they are there and generates new ones.

**Comment by t-b** [comment]
@oruebel Yes that was the original problem. Obviously wrong name is the same effect than non existing.

**Comment by rly** [comment]
@t-b Is this still an important issue to resolve? To summarize the issue: if an NWB object does not have an "object_id" attribute, then on each read, it is set to a randomly generated value that will be different on each read. 

One solution is to open the NWB file that contains missing "object_id" attributes with `nwbfile = io.read()`, call `nwbfile.set_modified()`, and call `io.write(nwbfile)` to add the missing "object_id" attributes to the NWB file. I have not tested that, but it should work. Subsequent reads of this file will read those "object_id" values and not make new ones.

I think this would be better than creating PyNWB/HDMF objects on read and NOT setting "object_id" to some value because "object_id" is used for other HDMF features, like linking objects to external resources.

Please reopen if this is important to resolve.
