### ISSUE TITLE
Removing items from a LabelledDict

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#404]
PyNWB uses `LabelledDict` in `MultiContainerInterface`. A `MultiContainerInterface` type can contain any number of `LabelledDict`. For example, `NWBFile` contains one for the acquisition group, the analysis group, the processing group, and so on.

With the recent addition of export to HDMF, users wish to remove items from a group, e.g., remove a `TimeSeries` from the `acquisition` group. What should the interface be for this?

Option 1:
I think the most intuitive and pythonic ways to do this are to call `del nwbfile.acquisition['my_timeseries']` or `nwbfile.acquisition.pop('my_timeseries')`. Currently, this will not remove the `TimeSeries` properly because the parent, `NWBFile`, needs to know that that child has been removed, but we can modify the `__delitem__` and `pop` methods of `LabeledDict` to call `parent._remove_child(child)`.

Option 2:
`MultiContainerInterface` creates methods for adding an item to a group (`add_acquisition`), getting an item (`get_acquisition`), and accessing the attribute (`.acquisition`). We could add a method for removing an item (`remove_acquisition`) which removes the item from the dict and calls `parent.remove_child(child)`. This is more consistent with the current API. Consistency is important, but I am personally not a fan of this method because it would add at least 13 methods to the already bloated [NWBFile API](https://pynwb.readthedocs.io/en/stable/pynwb.file.html) which has 50+ methods. 

Note: I understand that the `create_*` methods are based off of h5py. h5py does not have `remove_*` methods but favors the `del group['name']` syntax.

Which method would be better?

**Comment by bendichter** [comment]
Thanks for working on this and thinking about it so carefully, @rly. I think either option would work, but I agree with you that I like option 1 more. We could also allow for both, but then that would be ever more methods to worry about.

**Comment by oruebel** [comment]
I agree that we should choose one the two options (not both).  I don't have a particularly strong preference for either option in this case (I can see pros/cons for either). Option 1 is fine with me. I just want to bring up a couple of pitfalls that I can see, just in case these are actual issues:

1. Option 1 seems to assume that any given TimeSeries appears in only one LabeledDict. In practice ``parent._remove_child(child)`` should only be called from the LabeledDict with the parent of the LabeledDict and the parent of the child are the same. Otherwise if a TimeSeries appears in multiple LabeledDicts, you may end up removing it from the wrong parent. Not sure how often this would happen in practice, but it seems like all I need to do is used LabeledDict in my own code (outside of HDMF) to trigger this issue.
2. I have a question about ``del nwbfile.acquisition['my_timeseries']``. Usually this means that only the key ``my_timeseries`` is being removed from the LabeledDict. Are you implying that the ``TimeSeries`` object itself is being deleted as well, or would that be still around (as long as I have a reference to it)? Either way, I think we should separate deleting the key from deleting the value.

**Comment by rly** [comment]
> 1. Option 1 seems to assume that any given TimeSeries appears in only one LabeledDict. In practice `parent._remove_child(child)` should only be called from the LabeledDict with the parent of the LabeledDict and the parent of the child are the same. Otherwise if a TimeSeries appears in multiple LabeledDicts, you may end up removing it from the wrong parent. Not sure how often this would happen in practice, but it seems like all I need to do is used LabeledDict in my own code (outside of HDMF) to trigger this issue.

Yes, please see my implementation in #405 and the following code that would be added in MultiContainerInterface:
```python
    @docval(*get_docval(NWBDataInterface.__init__))
    def __init__(self, **kwargs):
        call_docval_func(super(MultiContainerInterface, self).__init__, kwargs)

        # call this function whenever a container is removed from the dictionary
        def _remove_child(child):
            if child.parent is self:
                self._remove_child(child)

        if isinstance(self.__clsconf__, dict):
            attr_name = self.__clsconf__['attr']
            self.fields[attr_name] = LabelledDict(attr_name, remove_callable=_remove_child)
```

> 2. I have a question about `del nwbfile.acquisition['my_timeseries']`. Usually this means that only the key `my_timeseries` is being removed from the LabeledDict. Are you implying that the `TimeSeries` object itself is being deleted as well, or would that be still around (as long as I have a reference to it)? Either way, I think we should separate deleting the key from deleting the value.

Yes, it means the key would be deleted, but if the child exists only in the group it is being deleted from, then the child is essentially deleted. In the example, if NWBFile is the parent of the TimeSeries that is being deleted from the acquisition group, then the child would be removed, and assuming nothing else is pointing to the TimeSeries, it would not get written. This raises a good point about handling references/links. I think an error would be thrown if a file is written with a link/reference to an object that does not have a parent and is therefore not written to the file, but I need to check.

If NWBFile is not the parent of the TimeSeries, then the file has a link to the TimeSeries, and only the link would be deleted from the acquisition group.

**Comment by oruebel** [comment]
@rly thanks for the clarification. Looks good.
