### ISSUE TITLE
Add support for h5py 3

### ISSUE THREAD

**Issue by ajtritt** [hdmf-dev/hdmf#458]
h5py has released 3.0 and is already on 3.1. I am opening this issue to keep track of things we will need to be aware of as we move to support h5py 3

- [ ] You can no longer set a `list` of `str` as an attribute directly. It needs to be converted to a numpy array with a `h5py.special_dtype`. HDMF will need to be modified here to support this:
https://github.com/hdmf-dev/hdmf/blob/729746025f8cc27e96d02384c8cc4d9830284651/src/hdmf/backends/hdf5/h5tools.py#L859

- [ ] Datasets of variable length strings, whether UTF-8 or ASCII, get returned as a `bytes` object. 
  - check if h5py >= 3.0, use `h5py.Dataset.asstr()` wrapper and add that to docval macro `array_data`. `AsStrWrapper` does not allow write and does not inherit from `h5py.Dataset` so we either tell users to call `.asstr()` on read or we add a wrapper class that does this behind the scenes (best option). Both options are a major version bump. 
  - If we go this route, we may as well remove support for lists and tuples and require numpy arrays, which removes many edge cases and complexity. We can deprecate gradually by raising a warning whenever a list is used and saying it is being converted to a numpy array of dtype x.

- [ ] In previous versions, creating a dataset from a list of bytes objects would choose a fixed length string datatype to fit the biggest item. It will now use a variable length string datatype. To store fixed length strings, use a suitable dtype from h5py.string_dtype().
  - this probably does not affect us. we always store vlen strings.

**Comment by t-b** [comment]
@ajtritt I'm looking forward to do read tests on the NWB files MIES creates with a PR using h5py >= 3.0.

**Comment by bendichter** [comment]
These items from [the release logs](https://docs.h5py.org/en/stable/whatsnew/3.0.html#breaking-changes-deprecations) seem to require attention:

> Variable-length UTF-8 strings in datasets are now read as bytes objects instead of str by default, for consistency with other kinds of strings. See Strings in HDF5 for more details.

> In previous versions, creating a dataset from a list of bytes objects would choose a fixed length string datatype to fit the biggest item. It will now use a variable length string datatype. To store fixed length strings, use a suitable dtype from h5py.string_dtype().

**Comment by ajtritt** [comment]
> In previous versions, creating a dataset from a list of bytes objects would choose a fixed length string datatype to fit the biggest item. It will now use a variable length string datatype. To store fixed length strings, use a suitable dtype from h5py.string_dtype().

I'm fairly certain we don't ever let h5py determine data type, we always specify it, so I don't think this will be an issue. I will add it to the list above to make sure we double check that

**Comment by oruebel** [comment]
@ajtritt @rly FYI, a related issue reported on the ndx-icephy-meta repo https://github.com/oruebel/ndx-icephys-meta/issues/81

**Comment by sneakers-the-rat** [comment]
This now breaks installation for python>=3.9 -- with the old setuptools deprecated, `pip install` no longer triggers the installation of Cython from this relatively weak check: https://github.com/h5py/h5py/blob/1156f5ac1ca38db85dcd906cf19a7aba90d0b39a/setup.py#L39

and PEP 517 installers and dependency solvers won't detect it either. wheels are only available up to python 3.8: https://pypi.org/project/h5py/2.10.0/#files

h5py 3.0 is about a year and a half old, wondering what's holding this back? a fix in the meantime that could compensate for it is requiring Cython for python>3.9.

This doesn't seem to break typical pip installation for pynwb because it requires >=2.9,<4 https://github.com/NeurodataWithoutBorders/pynwb/blob/a11cc3fce860c0b6398e082c66b2c26ec1e3a120/setup.py#L22

but that means that the install requirements are inconsistent (as has been mentioned in other issues). So in that case, a typical pip install of pynwb will install latest h5py, but a correct dependency resolution (using poetry at the moment) will pin 2.9, so this also breaks pynwb.

related to https://github.com/NeurodataWithoutBorders/pynwb/issues/1319

**Comment by sneakers-the-rat** [comment]
(edit: my bad for previous comment saying this breaks install on python >=3.9, was a problem with the yanked pynwb 2.5.1 release, which is poetry's problem not y'alls <3 )

**Comment by oruebel** [comment]
It looks like this issue wasn't closed when h5py 3 support was added in HDMF. Closing this issue now.

This issue has been resolved in the HDMF 3.0 release in Jul, 2021. The [HDMF 3.0 release](https://github.com/hdmf-dev/hdmf/releases/tag/3.0.0) added h5py 3.x support which was part of the following PR https://github.com/hdmf-dev/hdmf/pull/480 HDMF currently.
