### ISSUE TITLE
[Feature]: Change the external resources file name

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#911]
### What would you like to see added to HDMF?

As far as I can tell, the name of the written, normalized, external resources file is `er.zip`. I get why we can't use a particular NWB file name -- because ExternalResources can go across files. But can we name this something more descriptive, like NWB_External_Resources.zip? Or allow the user to customize the name of this file on write and read? Currently, it looks like you can only customize the directory that this file will be written in.

### What solution would you like?

Probably would be best to allow the user to customize the name of the ExternalResources .zip file on write and read

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by oruebel** [comment]
I think allowing a user to specify the filename directly would be best. I think the folderpath is just a carryover before norm_tsv was using zip and was generating multiple files as output. In terms of changes I think it would be good to:

1. Updated ``to_norm_tsv`` and ``from_norm_tsv`` to take the filepath for the zipfile as input (rather than the folder) so that a user can control the filename. 
2. Update ``HDFMIO`` accordingly (i.e,. ``.__init__()``, ``read()``, ``write()`` to accept the filename (this may be a no-op, since HDMFIO probably just passes the path to ``to/from_norm_tsv``)

Optionally we could also:

3. Allow the user to set the path for external resources in ``HDMFIO`` to true to indicate that they want to either: 1) write the ER file using the same path (but different file extension) as the NWBFile if this is a new ER file or 2) write the ER file to the same location it was read from if it is an existing ER file. In this way, this would cover both the case where a user wants to create one ER file per NWBFile and the case where a user is using the same ER file for multiple NWB files. 
4. On a separate (but related note), we may want to allow in ``to_norm_tsv`` for the user to configure whether the files should be zipped or placed into a folder. I like the convenience of a single zip file, but I don't think Git can handle versioning/diffing the contents of zip files, so for the case where a user want's to version-control the ER files, it would be useful to store them as separate TSV files.

**Comment by mavaylon1** [comment]
1&2 make sense. As for 4, I will pull the crowd at the workshop to see if version control is something they will use. As for 3, it makes sense. However, I do think having the path variable already there is the most flexible/the user has the most control (and in a way can be set to the NWBFile path and so already included this functionality), but I am not against making it more explicit.

**Comment by oruebel** [comment]
@mavaylon1 makes sense. I would suggest we make the changes for 1 & 2. And for 3 & 4 we can wait on user feedback.

**Comment by mavaylon1** [comment]
@oruebel I suppose with the ability to name to the zip file would allow users to set a version in the name. (commenting on your suggestion 4). A version control on the IO alone would be just appending some information to the name correct? Or do you want to go deeper and have a version parameter on ExternalResources that will then be used as part of the name on write. The surface level IO parameter doesn't allow users to see the version unless they look a the file name and not directly, leaving the latter suggestion as the one that makes most sense to me. 

I'm thinking about how to phrase the question to the users this week: "Do you want version control as a parameter" or just "do you want the ability to write to files and not just zip". The custom name change (as mentioned prior) would let users keep track of versioning on the file level already and so an IO version parameter doesn't makes sense.

**Comment by mavaylon1** [comment]
@oruebel as for 3) I am going to only ask for the second option "write the ER file to the same location it was read from if it is an existing ER file. In this way, this would cover both the case where a user wants to create one ER file per NWBFile and the case where a user is using the same ER file for multiple NWB files."

This way supports both file cases and the other does not.

**Comment by oruebel** [comment]
> I suppose with the ability to name to the zip file would allow users to set a version in the name

The key issue with versioning using Git is that it allows tracking of diff's to see exactly what parts of file changed between versions and when. I.e., the issue is less about storing version numbers and more about tracking changes over time. We can discuss this topic during the hackathon. 

> as for 3) I am going to only ask for the second option "write the ER file to the same location it was read from if it is an existing ER file. In this way, this would cover both the case where a user wants to create one ER file per NWBFile and the case where a user is using the same ER file for multiple NWB files."

Sounds good.

**Comment by mavaylon1** [comment]
> > I suppose with the ability to name to the zip file would allow users to set a version in the name
> 
> The key issue with versioning using Git is that it allows tracking of diff's to see exactly what parts of file changed between versions and when. I.e., the issue is less about storing version numbers and more about tracking changes over time. We can discuss this topic during the hackathon.

Ah I see what you mean. Maybe a good middle ground is to write both the zip and the files. The zip file is a lot easier to share or upload and the explicit files would allow the user to keep track on Git. This would most likely require `read` to support both as well.

**Comment by oruebel** [comment]
> Maybe a good middle ground is to write both the zip and the files.

I think we could just make it flag on the write function `zip=True` which would be `True` by default. I.e., when `zip=False` we would write a folder with the TSV files and if `zip=True` we would zip the files. 

> This would most likely require `read` to support both as well.

Yes, read would need to support this too. However, here we probably don't need a separate flag, because we can simply check whether the input path is a file or a folder, e.g., 

```
if os.path.isfile(input_path):
    # read tsv files from zip
else:
    # read tsv files from folder
# parse the tsv data
```

**Comment by mavaylon1** [comment]
@oruebel @rly This is on my radar now that we have some feedback from dev days. I am talking with Cody this Wednesday to flush some Dandi requirements, but the general ability to name the file is something we'd want in general. I'll have a draft PR Friday due to other items coming first on to-do list.
