### ISSUE TITLE
[Feature]: TermSet Restructure Part 3

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf#929]
### What would you like to see added to HDMF?

Once part 1 and 2 are merged, adjustments may need to be made such that all containers for PyNWB pass this wrapper update along with adding the unwrapping functionality so that the wrapper does not interfere with `write`.

This may lead to adjustments to the `BuildManager`.

More details will follow after 1&2 have been developed. 

### What solution would you like?

Refer above

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by oruebel** [comment]
> This may lead to adjustments to the `BuildManager`.

The idea here is that the I/O backend does not need to know about TermSet's because this is only relevant for HERD files, which are written separately. So when creating builders for I/O we could simply "unwrap" the data so that nothing changes for the I/O backend. 

Alternatively, the HDF5IO and ZarrIO backends would need to be updated to handle the case of wrapped datasets correctly. 

> adjustments may need to be made such that all containers for PyNWB pass this wrapper update

I would expect that the main issues here are likely: 1) passing docval (which should be a simple fix in HDMF), and 2) passing the various validation and data processing that the PyNWB classes want to do, e.g., when we check in `__init__` that data values are correct or aligned with other fields.
